### ISSUE TITLE
Find a better way of managing header and footer, or a base page in general

### ISSUE THREAD

**Issue by TylerHobanDotCom** [TriHardspace/Mainsite#12]
It's shit to deal with without a macro and I don't want to spend the time making a macro for a shitty static dumpster fire. Also, who the fuck do you think I am I do all of this shit from the fucking browser, not because I hate native but because I hate git.

**Comment by levelfourtwenty** [comment]
Fixed with 1b91a1f1f59223ac593de12cf4ebf1c05fb4747c and ed4bf656af836e839769fca736ace3730a786d45.
