### ISSUE TITLE
Add "Get Involved" and "Support" tabs to header, update policies with new support info

### ISSUE THREAD

**Issue by TylerHobanDotCom** [TriHardspace/Mainsite#21]
Finish #12 before both dropdowns
Get Involved>Dropdown
- Contribute Financially>/donate
- Contribute your time>Volunteer Tasks Trello Board
- Contribute Content>Content Wanted List Trello Board

Support>Dropdown
- via Discord>Community Support Server
- via Telegram>t.me/TriSupportBot
- via Mail>registered agent information (popup box?)

Policies:
- finish #20 
- add same info as support dropdown in /tos /privacy /takedown

**Comment by levelfourtwenty** [comment]
Fixed on 4c8f4335038a6e230873ceb74bd3ed0f14b764d0.

**Comment by TylerHobanDotCom** [comment]
Support is a copy of Telegram xd

**Comment by TylerHobanDotCom** [comment]
Fixed, dont know when
